### ISSUE TITLE
This project needs a quick start guide

### ISSUE THREAD

**Issue by beornharris** [artipie/front#123]
I am not a Java programmer, and just want to get/try the front end to Artipie.

Can you pleasde add a short "Getting Started" guide that outlines how to build / deploy (ideally containerised)

After more time than it should have taken I was able to build the project (`mvn package`) but now I have a jar file, it is not clear to me how to deploy - what is the container/web server etc?

Many Thanks

**Comment by olenagerasimova** [comment]
https://github.com/artipie/artipie?tab=readme-ov-file#quickstart

**Comment by ChGen** [comment]
Done
