### ISSUE TITLE
Parse artipie configuration file

### ISSUE THREAD

**Issue by g4s8** [artipie/front#3]
Parse Artipie YAML configuration file from `/etc/artipie/artipie.yml` and create `Storage` instance based on these files (maybe create `BlockingStorage` instead of `Storage`).

**Comment by olenagerasimova** [comment]
@g4s8 why do we need to parse artipie configuration yaml here? We did not need this yaml in management-api and we have `Settings` interface and `YamlSettings` implementation for this in artipie/artipie...

**Comment by g4s8** [comment]
> @g4s8 why do we need to parse artipie configuration yaml here? We did not need this yaml in management-api and we have `Settings` interface and `YamlSettings` implementation for this in artipie/artipie...
> 
> If we do need artipie yaml settings here, I'd suggest to move `Settings` interface from artipie here...

@olenagerasimova we need to use storage with main configuration files here (repositories, permissions, etc). Coordinates of this storage is located in primary `artipie.yml`. How do you suggest to parse it?
