### ISSUE TITLE
Design a public REST API

### ISSUE THREAD

**Issue by g4s8** [artipie/front#5]
Design public API for repositories, users, permissions and storage:
 - `/repositories/{name}` - for repositories
 - `/users/{name}` - for users
 - `/permissions/{name}` - for permissions
 - `/storage/{name}` - for storage

All APIs are REST APIs with standard resource semantic. Support `GET`, `PUT`, `HEAD`, `DELETE` methods, e.g.:
 - `GET /repositories` - list all repositories
 - `GET /repositories/{name}` - get repository details
 - `PUT /repositories/{name}` - creates new repository from payload (if no conflicts)
 - `HEAD /repositories/{name}` - check repository exist (200 or 404 status)
 - `DELETE /repositories/{name}` - delete repository by name

Let's start with some core design of these APIs, and then we decompose it to smaller tasks.

**Comment by olenagerasimova** [comment]
@g4s8 here is significant question: this API should work only for `org` layout or for any?

**Comment by g4s8** [comment]
> @g4s8 here is significant question: this API should work only for `org` layout or for any?

@olenagerasimova for any. But I think we can hide these details from API user, e.g. `GET repositories` API may return the list of repositories like:
```json
[
  {
    "fullName": "org1/repo1"
  },
  {
    "fullName": "org1/repo2"
  },
  {
    "fullName": "org2/repo1"
  },
  {
    "fullName": "org2/repo2"
  }
]
```
And then client can use repository names as strings without parsing `org` from this: `GET /repositories/org1/repo2`.

And same for flat structure:
```json
[
  {
    "fullName": "repo1"
  },
  {
    "fullName": "repo2"
  }
]
```

**Comment by olenagerasimova** [comment]
@g4s8 sure, we can hide the details. But in the case of `org` layout `org1` and `org2` from your examples are usernames, and I'm not sure we should list to John repositories of Jane (at least now we show the user only his repositories). 

Also, let me remind you, that we have a separate file `_permissions.yaml` with permissions for to access API endpoints. Maybe, should extend it now and add permissions to see repositories/settings for any user.

**Comment by g4s8** [comment]
> @g4s8 sure, we can hide the details. But in the case of `org` layout `org1` and `org2` from your examples are usernames, and I'm not sure we should list to John repositories of Jane (at least now we show the user only his repositories).
> 
> Also, let me remind you, that we have a separate file `_permissions.yaml` with permissions for to access API endpoints. Maybe, should extend it now and add permissions to see repositories/settings for any user.

@olenagerasimova sure, we need some kind of permissions to view repositories, e.g. if John has permission to see one of Jane's repository, then he will see it in `GET /repositories` list.

**Comment by olenagerasimova** [comment]
@g4s8 ok, then we need to design this permissions too. Or, for now, we can simply distinguish two types of users: users, who can see only their repositories/permissions/storages and users, who can see all info. What do you think?

**Comment by olenagerasimova** [comment]
@g4s8 ok, another question: how we return\accept repository setting? As plain yaml or as a field of some json?

**Comment by g4s8** [comment]
> @g4s8 ok, another question: how we return\accept repository setting? As plain yaml or as a field of some json?

@olenagerasimova I think we can use JSON structure for this, e.g. include name and other repository options (like proxy repo URIs, etc).I'm not sure about permissions, because we may want to have granular permission's management for this, so if a user has access to repository details but doesn't have it for permissions, then we shouldn't return permission's configuration in `GET /repository/<name>` but we may have separate handle for this `/repository/<name>/permissions` to accept read and edit requests.

**Comment by olenagerasimova** [comment]
@g4s8 ok, got it

**Comment by olenagerasimova** [comment]
@g4s8 let's discuss how `/permissions/{name}` endpoints should work, `name` here stands for username or repository name? If it's a username I suppose the `GET /permissions/{name}` should return repositories and permissions user have in the repository, for example:
```json
{
  "maven-internal": ["read", "write"],
  "go-central": ["read"],
  "files-storage": ["*"]
}
```
`POST` endpoint can accept json of the same format and set received permissions to the repositories for user with uid `{name}`. `DELETE` can remove all permissions for user in all repositories.

**Comment by g4s8** [comment]
> @g4s8 let's discuss how `/permissions/{name}` endpoints should work, `name` here stands for username or repository name? If it's a username I suppose the `GET /permissions/{name}` should return repositories and permissions user have in the repository, for example:
> 
> ```json
> {
>   "maven-internal": ["read", "write"],
>   "go-central": ["read"],
>   "files-storage": ["*"]
> }
> ```
> 
> `POST` endpoint can accept json of the same format and set received permissions to the repositories for user with uid `{name}`. `DELETE` can remove all permissions for user in all repositories.

@olenagerasimova maybe we can move `permissions` API to related resource? E.g. if we want to check repo permissions, then we call `GET /repo/{repo}/permissions` which returns users with permissions for `{repo}` repository (this API should be easy enough). We can't get user's permissions efficiently, because of complexity: we need to iterate over each repository to check user's permissions. So I'm suggesting to create new logic for grant and revoke of user's permissions: when we add "user" to "repository" with "permissions", then we do two things: 1) add entry to "repository" config to grant/revoke permissions of "user"; 2) we add a link of "repository" to "user's" scope (similar to GItHub fork mechanism), e.g. if "user" `alice` get access in "repository" `bob/maven`, then we add permission entry to `bob/maven` configuration and add (or update in case if add new permission; or delete if revoke permission) a repository configuration to `alice/maven`, e.g.:
```yaml
repo:
  type: link
  target: bob/maven
```
Then we can efficiently get all user's repositories and check permissions. WDYT?

**Comment by olenagerasimova** [comment]
@g4s8 I agree and understand the first part about `repo/{repo}/permissions` endpoint. I do not understand the second part and suggested yaml format.

Also, let me remind you, that we have user groups and it's possible to grant permission for the repository to a group:
```yaml
repo:
  type: maven
  permissions:
    alice:
      - read
    /admin:
      - "*"
```
group in `permissions` section of repository settings yaml is indicated with `/` sign, check the [docs](https://github.com/artipie/artipie#repository-permissions)

**Comment by g4s8** [comment]
@olenagerasimova OK, let's start with API for repo permission first, and then think about user's permissions.

I think we can use `GET` method as you suggested, I don't think `POST /repo/{repo}/permissions` is a good method for this case, so maybe we can use `PUT /repo/{repo}/permissions/{user}` and `DELETE /repo/{repo}/permissions/{user}` with JSON array of permissions to grant/revoke permissions in`{repo}` for particular `{user}` (or group); and we also can accept `PATCH /repo/{repo}/permissions` method for batch update operation, e.g.:

Grant `read` permissions to `bob` in `alice/maven` repo:
```http
PUT /repo/alice/maven/permissions/bob

["read"]
```

Revoke `read` and `write` permissions:
```http
DELETE /repo/alice/maven/permissions/bob

["read", "write"]
```

Grant `read` permission to `bob` and `john` but revoke `write` permission for `john`:
```http
PATCH /repo/alice/maven/permissions

{
  "grant": {
    "bob": ["read"],
    "john": ["read"]
  },
  "revoke": {
    "john": ["write"]
  }
}
```

**Comment by olenagerasimova** [comment]
@g4s8 I'd suggest to simplify `DELETE` method: let's do not accept any json body and simply revoke all the permissions for user. Otherwise, it's more like `PATCH`, not `DELETE`.

**Comment by g4s8** [comment]
@olenagerasimova OK, agree
